"""Initial migration

Revision ID: 37cfe3dba0c5
Revises: a09e4a761c85
Create Date: 2025-09-16 18:59:52.442716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37cfe3dba0c5'
down_revision = 'a09e4a761c85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bank_service')
    op.drop_table('transaction')
    op.drop_table('user')
    op.drop_table('loan_application')
    with op.batch_alter_table('loan_applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loan_applications', schema=None) as batch_op:
        batch_op.drop_column('password_hash')

    op.create_table('loan_application',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('application_id', sa.VARCHAR(length=20), nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('mother_name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('father_name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('gender', sa.VARCHAR(length=10), nullable=False),
    sa.Column('date_of_birth', sa.DATE(), nullable=False),
    sa.Column('aadhar_number', sa.VARCHAR(length=12), nullable=False),
    sa.Column('pan_number', sa.VARCHAR(length=10), nullable=True),
    sa.Column('mobile_number', sa.VARCHAR(length=10), nullable=True),
    sa.Column('loan_type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('loan_amount', sa.FLOAT(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('email', sa.VARCHAR(length=100), nullable=True),
    sa.Column('address', sa.TEXT(), nullable=True),
    sa.Column('photo_url', sa.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('application_id')
    )
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=80), nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=120), nullable=False),
    sa.Column('role', sa.VARCHAR(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('transaction',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('amount', sa.FLOAT(), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bank_service',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('service_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('interest_rate_min', sa.FLOAT(), nullable=True),
    sa.Column('interest_rate_max', sa.FLOAT(), nullable=True),
    sa.Column('processing_time', sa.VARCHAR(length=50), nullable=True),
    sa.Column('features', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
