"""Auto migration on 20251109_203555

Revision ID: 412256f38609
Revises: 1c35cf368964
Create Date: 2025-11-09 20:36:01.810603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '412256f38609'
down_revision = '1c35cf368964'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_user_email', ['email'])
        batch_op.create_unique_constraint('uq_user_fullname', ['full_name'])
        batch_op.create_unique_constraint('uq_user_username', ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_username', type_='unique')
        batch_op.drop_constraint('uq_user_fullname', type_='unique')
        batch_op.drop_constraint('uq_user_email', type_='unique')

    # ### end Alembic commands ###
