"""Auto migration on 20251109_204241

Revision ID: 8af5ca867306
Revises: 412256f38609
Create Date: 2025-11-09 20:42:43.131350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8af5ca867306'
down_revision = '412256f38609'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_users')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_user_email', ['email'])
        batch_op.create_unique_constraint('uq_user_fullname', ['full_name'])
        batch_op.create_unique_constraint('uq_user_username', ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_username', type_='unique')
        batch_op.drop_constraint('uq_user_fullname', type_='unique')
        batch_op.drop_constraint('uq_user_email', type_='unique')

    op.create_table('_alembic_tmp_users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=80), nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=128), nullable=False),
    sa.Column('full_name', sa.VARCHAR(length=150), nullable=True),
    sa.Column('email', sa.VARCHAR(length=150), nullable=True),
    sa.Column('role', sa.VARCHAR(length=50), nullable=False),
    sa.Column('bank_id', sa.INTEGER(), nullable=True),
    sa.Column('branch_id', sa.INTEGER(), nullable=True),
    sa.Column('last_login', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('created_by', sa.VARCHAR(length=100), nullable=True),
    sa.Column('modified_by', sa.VARCHAR(length=100), nullable=True),
    sa.ForeignKeyConstraint(['bank_id'], ['cooperative_banks.id'], ),
    sa.ForeignKeyConstraint(['branch_id'], ['cooperative_branches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', name='uq_user_email'),
    sa.UniqueConstraint('full_name', name='uq_user_fullname'),
    sa.UniqueConstraint('username', name='uq_user_username')
    )
    # ### end Alembic commands ###
